### ISSUE TITLE
Crashes on Android just after build and run without any errors

### ISSUE THREAD

**Issue by zarincheg** [react-native-picker/picker#85] opened 2020-05-20 13:25 UTC
Hello! 

I used the last version with React 16.9.0, RN 0.61.2, and Android 8.1/9 (real device and emulator) and it crashes the app after build and starts. No errors in the console output. 

I also tried an older version until 1.1.3 and the issue still happens.

**Comment by ApostolisGaros** [comment] 2020-05-21 10:04
Same problem here

**Comment by AlcantaraRW** [comment] 2020-05-22 03:09
Same here...

**Comment by hoc-ht** [comment] 2020-05-25 08:55
Same here...

**Comment by yamifr07** [comment] 2020-06-01 20:36
Same here!

**Comment by harveyappleton** [comment] 2020-06-05 14:15
Same here, works fine on iOS

**Comment by nabilalilipaly** [comment] 2020-07-02 09:36
same here

**Comment by thecodecafe** [comment] 2020-07-02 17:14
Same thing I'm experiencing here.

**Comment by Naturalclar** [comment] 2020-07-02 23:18
@zarincheg hello :wave: sorry for causing you trouble. I wasn't able to reproduce the error on my side. Could you create a repository that reproduces the error?

**Comment by amphyxs** [comment] 2020-07-29 08:27
The same to me. I launched the app on Android 10 phone and it crashed without error messages. But when I moved to Android 9 device it worked without errors.

**Comment by nicholas-fieschko** [comment] 2020-10-04 19:03
This was happening to me, and I found that it was due to passing a `label` prop to `Picker.Item` that was a number instead of a string. When I cast the label to a string before passing it in, it stopped crashing.
May or may not be the case any of you were encountering, but hope this helps anyone in the same scenario.

**Comment by MichaelArriaga** [comment] 2020-10-14 19:07
@nicholas-fieschko this fixed the issue for me. I was passing an integer to the label prop. Thank you!

**Comment by aliraza-noon** [comment] 2021-02-05 09:26
same here

**Comment by jdcaacbay-wp** [comment] 2021-03-17 09:48
Anyone having the same problems? This is still happening to me. After adding the package, it builds without error, but it crashes (android)

**Comment by Naturalclar** [comment] 2021-04-01 02:47
Closing due to lack of information.

For anyone having trouble, please try the following methods.

> This was happening to me, and I found that it was due to passing a label prop to Picker.Item that was a number instead of a string. When I cast the label to a string before passing it in, it stopped crashing.
May or may not be the case any of you were encountering, but hope this helps anyone in the same scenario.

If that does not work, please provide a sample repository that can reproduce the issue. thank you!

**Closed by Naturalclar** 2021-04-01 02:47 UTC

**Comment by aliraza-noon** [comment] 2021-04-01 05:51
@Naturalclar why rush to close this, what you referring to is not a solution it is more like a hack.
