### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager.

### ISSUE THREAD

**Issue by CaptainJeff** [react-native-picker/picker#45] opened 2020-01-09 19:29 UTC
# Bug

I am unable to get this to work. I'm receiving the following error

`Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager.

This error is located at:
    in RNCPicker (at PickerIOS.ios.js:107)
    in RCTView (at View.js:35)
    in View (at PickerIOS.ios.js:106)
    in PickerIOS (at Picker.js:142)
    in Picker (at edit-exercise.modal.tsx:54)
    in EditExerciseModal (created by inject-with-exerciseStore(EditExerciseModal))
    in inject-with-exerciseStore(EditExerciseModal) (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:909)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:984)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:393)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:383)
    in PanGestureHandler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:35)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:909)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:984)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:393)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:383)
    in PanGestureHandler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:35)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at root-component.tsx:73)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:163)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at root-component.tsx:71)
    in BackButtonHandler (at root-component.tsx:70)
    in MobXProvider (at root-component.tsx:69)
    in RootComponent (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)`
## Environment info

    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 18.22 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Describe what you expected to happen:

I expected the spinner to show but i received this error. I used the sample code in the readme

**Comment by freeworlder** [comment] 2020-01-11 11:15
Hi,
The same here. It is working on android but on iOS it returns the error.
I am using expo 34.

**Comment by jainkuniya** [comment] 2020-01-11 21:10
Hi, it will be great if you could share some demo project or expo link, where this is reproducible.

**Comment by alexhoo** [comment] 2020-01-17 12:09
Same issue here. Expo SDK 36

**Comment by flatcoke** [comment] 2020-01-20 05:59
_Restart_ your simulator after pod install

**Comment by emmanuel-cbqa** [comment] 2020-02-13 16:14
> Restart your simulator after pod install

Same error.
I tried this and it still doesn't work for me.

**Comment by john-harding** [comment] 2020-02-18 05:42
Getting this as well

**Comment by cornelRaiu** [comment] 2020-03-15 00:31
Hi there. Any news regarding this issue?

**Comment by Naturalclar** [comment] 2020-03-17 08:20
`Picker` component is indeed deprecated but still exists in the react-native core repository. Until the picker component is fully removed from the core, usage of `react-native-picker` on a managed workflow of `expo` will probably not be supported.

If you are using bare workflow with `expo eject`, you may need to run `pod install` to install this package for iOS.

**Comment by sebastianknopp** [comment] 2020-04-24 07:50
> `Picker` component is indeed deprecated but still exists in the react-native core repository. Until the picker component is fully removed from the core, usage of `react-native-picker` on a managed workflow of `expo` will probably not be supported.
> 
> If you are using bare workflow with `expo eject`, you may need to run `pod install` to install this package for iOS.

Any idea when this will happen?

**Comment by JiaqiGuo** [comment] 2020-04-26 03:14
In XCode, in the project navigator, select your project. Add libRNCPicker.a to your project's Build Phases ➜ Link Binary With Libraries
Then Build your project

**Comment by freeworlder** [comment] 2020-05-01 12:04
> In XCode, in the project navigator, select your project. Add libRNCPicker.a to your project's Build Phases ➜ Link Binary With Libraries
> Then Build your project

I suppose this is for ejected projects. Mine was non-ejected expo project.

**Comment by tills98** [comment] 2020-05-06 17:07
Same issue here. Using Expo SDK 37.

**Comment by karimcambridge** [comment] 2020-05-07 06:28
Getting this issue on iPhone XS, Expo SDK 37.

**Comment by fortydegrees** [comment] 2020-05-08 05:55
Have this issue with multiple components. Expo 37.

**Comment by SixStringsCoder** [comment] 2020-05-11 19:05
Same here Expo SDK 37

**Comment by mutavdzicm** [comment] 2020-05-12 11:03
Same problem Expo SDK 37

**Comment by MorgadoKnivet** [comment] 2020-05-12 22:39
I solved this deleting the app from simulator and installing again with react-native run-ios

**Comment by Mariussuv** [comment] 2020-05-13 07:44
Not sure this is the case for you, but I imported it using "import {Picker} from '@react-native-community/picker';". And had the same problem for days now. But after changing to "import {Picker} from 'react-native';" it works fine now.

**Comment by digaso** [comment] 2020-05-13 07:50
> 
> 
> Not sure this is the case for you, but I imported it using "import {Picker} from '@react-native-community/picker';". And had the same problem for days now. But after changing to "import {Picker} from 'react-native';" it works fine now.

That's because react-native has their own picker but It is deprecated so they say to use this one

**Comment by mritzman-dg** [comment] 2020-05-13 21:43
Same here with non-ejected app

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1

**Comment by sbirkmyre** [comment] 2020-05-20 14:55
> Hi, it will be great if you could share some demo project or expo link, where this is reproducible.

You can have a look at it in my project [here](https://github.com/Lean-Logger/mobile). The specific file in question is [here](https://github.com/Lean-Logger/mobile/blob/create_exercise/src/screens/CreateExerciseScreen.js).

**Comment by ax0n-pr1me** [comment] 2020-05-23 23:26
same problem - latest expo.

**Comment by Naturalclar** [comment] 2020-05-24 01:35
As far as I know, this component is still not available in the managed workflow of expo 37.
In order to use this component, you would have to eject into a bare workflow, so that other native modules can be used.
If you want to use the Picker Component in managed workflow of expo, please import the `Picker` component directly from `react-native.

```
import { Picker } from 'react-native'
```

you may see a deprecated warning, but the component is still usable as it lives in the core.

**Comment by sbirkmyre** [comment] 2020-05-24 12:28
> As far as I know, this component is still not available in the managed workflow of expo 37.
> In order to use this component, you would have to eject into a bare workflow, so that other native modules can be used.
> If you want to use the Picker Component in managed workflow of expo, please import the `Picker` component directly from `react-native.
> 
> ```
> import { Picker } from 'react-native'
> ```
> 
> you may see a deprecated warning, but the component is still usable as it lives in the core.

Thanks for your comment. Will work with the picker directly from React Native. Do you know when this component will become available in the managed workflow of Expo 37?

**Comment by tsuki42** [comment] 2020-06-08 15:02
I too had this issue. [This](https://stackoverflow.com/a/61975204/7090742) stackoverflow answer solved mine.

**Comment by natural411** [comment] 2020-06-08 20:16
doing a new pod install fixed it for me

**Comment by lcruz09** [comment] 2020-06-18 10:05
Here are some steps that helped on solving it:
- Make sure you install new pods
- Uninstall the app on your emulator
- Clean a build your app again (I did using Xcode)
- Redeploy your app on the emulator

Hope this helps someone :). Pura vida!

**Comment by AhmedAbuelenin** [comment] 2020-07-02 13:03
The same problem here, hope this gets supported soon for expo users.
Thank you.

**Comment by alexhoo** [comment] 2020-07-02 13:19
Expo 38 sdk is out and part of its new features is the Picker 
https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee?gi=39cbe20deef6

have you tried this upgrade?

**Comment by sbirkmyre** [comment] 2020-07-02 13:39
> Expo 38 sdk is out and part of its new features is the Picker
> https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee?gi=39cbe20deef6
> 
> have you tried this upgrade?

Further down the page under "Third-Party Modules", they state that @react-native-community/picker is now available. So should definitely be a solution out there, depending what route you want to go down.

I previously just opted to go for the deprecated Picker from the React Native library. With this release I'll look into both the Expo Picker and the RN Community Picker. Will report back when I have.

**Comment by Oakshiro** [comment] 2020-07-03 08:17
I have already upgraded to Expo 38 sdk, and as far as i know, there are 2 options:
1.- Use the deprecated version:
import { Picker} from "react-native";

2.- Use the updated community version, which I can confirm it works in Expo 38 .
import {  Picker } from "@react-native-community/picker";

**Comment by AlanSl** [comment] 2020-07-06 16:05
I had a similar issue with expo 38.0.8:

> Violation: requireNativeComponent RNCAndroidDialogPicker was not found in the UIManager

Running `expo update` fixed it for me, which (among other things) did this to my `package.json`:

```diff
-    "@react-native-community/picker": "^1.6.5",
+    "@react-native-community/picker": "1.6.0",
```

So it looks like currently, the exact version `1.6.0` of the picker is supported and a patch release since there is incompatible with current Expo. I also had to import from the exact Picker file, not the index, to avoid https://github.com/react-native-community/react-native-picker/issues/109

The details of this are likely to change in patch releases but `expo update` _should_ resolve any such issues now that `@react-native-community/picker` is officially supported.

**Comment by cornelRaiu** [comment] 2020-07-06 17:18
@AlanSl this is exactly why I always install packages using `expo install package-name`.

For example, in this case, running the `expo install @react-native-community/picker` results in this in the terminal:

    Installing 1 SDK 38.0.0 compatible native module using npm.
    > npm install
    ... other details

And the package it installed was: `"@react-native-community/picker": "1.6.0"`

**Comment by sathwik77** [comment] 2020-07-10 10:12
Expo SDK 38.0.0 fixed this issue and they have mentioned about this in their [release docs](https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee) , but in IOS the picker always stays open.

**Comment by cornelRaiu** [comment] 2020-07-10 10:17
@sathwik77 this is the default behavior on iOS. You can try to replace it with the ActionSheet. 
That is what I did and it works perfectly. Way better UX than the always open picker.

[This is a starting point](https://stackoverflow.com/questions/41181683/react-native-ios-picker-is-always-open) and this is the [Action Sheet iOS documentation](https://reactnative.dev/docs/actionsheetios.html)

**Comment by sathwik77** [comment] 2020-07-10 10:22
@cornelRaiu Oh! ok thanks, I get it. Guess I have to use Action Sheet for IOS. But this issue can now be closed I guess as it is fixed by Expo in their latest release!

**Comment by mschipperheyn** [comment] 2020-07-12 13:48
You have to ensure that the version you install exactly matches the version expo supports. You can verify with `yarn why @react-native-community/picker`. E.g. if the supported version is 1.6.0, don't install 
`"@react-native-community/picker": "^1.6.0"` 
but use 
`"@react-native-community/picker": "1.6.0"`

**Comment by KhalidBhyan** [comment] 2020-08-04 16:14
I solved the issue with these steps
1. `import { Picker } from '@react-native-community/picker'`
2. stop any metro bundler/server
3. uninstall the expo app from your emulator/device
4. update expo CLI: `npm install -g expo-cli`
5. run `expo update`

it should work now when you run `expo start`

**Comment by PritiMaurya** [comment] 2020-08-05 09:43
In my case after install, 
npm install @react-native-community/picker --save

the error is gone and work perfect

**Comment by nicolashemonic** [comment] 2020-08-06 13:22
Same here on an ejected app, It seams the pod of `@react-native-community/picker` is missing. I was obliged to add it to my project's dependencies and running `npx pod-install` to solve the issue.

**Comment by Oliver-ke** [comment] 2020-08-10 04:56
Using the latest expo SDK and running `expo update`  fixes this issue for me

**Comment by bryantabaird** [comment] 2020-08-11 03:08
`expo install @react-native-community/picker` instead of `npm install @react-native-community/picker` helps too

**Comment by AngeloGiurano** [comment] 2020-08-12 06:34
Navigate to the `ios` subfolder and run `pod install`

**Comment by blackvd** [comment] 2020-08-26 18:32
I have the same problem with expo 38

**Comment by blueberry6401** [comment] 2020-08-26 18:34
I'm using https://github.com/lawnstarter/react-native-picker-select (not expo), it has dependency of this library, having issue as well
requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

**Comment by pmtu95** [comment] 2020-09-09 07:07
> I'm using https://github.com/lawnstarter/react-native-picker-select (not expo), it has dependency of this library, having issue as well
> requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

`npm i -s @react-native-community/picker`
`cd ios/`
`pod install`

restart app will fixed this issue

**Comment by Milkhan** [comment] 2020-09-17 08:21
1- Stop the metro
2- Run react-native run-ios again.

**Comment by dantls** [comment] 2020-09-19 19:18
> expo install @react-native-community/picker


Some heroes don't wear a cape!!!

**Comment by mrbrunelli** [comment] 2020-09-23 18:17
> I solved the issue with these steps
> 
> 1. `import { Picker } from '@react-native-community/picker'`
> 2. stop any metro bundler/server
> 3. uninstall the expo app from your emulator/device
> 4. update expo CLI: `npm install -g expo-cli`
> 5. run `expo update`
> 
> it should work now when you run `expo start`

Work for me! :smile:

**Comment by karimcambridge** [comment] 2020-09-23 21:06
Check the changelog, https://github.com/expo/expo/blob/master/CHANGELOG.md

They updated the picker to 1.6.6.

This is solved.

**Comment by quy-setjapan** [comment] 2020-10-07 02:03
> `expo install @react-native-community/picker` instead of `npm install @react-native-community/picker` helps too

You are saving my life

**Comment by develiasdaniel** [comment] 2020-10-07 03:19
> > Estoy usando https://github.com/lawnstarter/react-native-picker-select (no expo), tiene dependencia de esta biblioteca, y también tiene un problema 
> > requireNativeComponent: "RNCAndroidDialogPicker" no se encontró en el UIManager.
> 
> @ arándano6401
> `npm i -s @react-native-community/picker`
> `cd ios/`
> `pod install`
> 
> reiniciar la aplicación solucionará este problema

for android works too!!!!!!! Thankssss

**Comment by erikvanek** [comment] 2020-12-15 09:54
> You have to ensure that the version you install exactly matches the version expo supports. You can verify with `yarn why @react-native-community/picker`. E.g. if the supported version is 1.6.0, don't install
> `"@react-native-community/picker": "^1.6.0"`
> but use
> `"@react-native-community/picker": "1.6.0"`

For those not using expo this seemed to solve the issue in my environment where I use `react-native@0.63.3`. Also do not forget to change the import path to `@react-native-community/picker`

**Comment by cornelRaiu** [comment] 2020-12-15 11:57
@erikvanek the `@react-native-community/picker` library has been renamed to `@react-native-picker/picker`

Here is the link to the new repo: [https://github.com/react-native-picker/picker](https://github.com/react-native-picker/picker)

**Comment by Mahdisaghroun** [comment] 2021-01-22 10:28
same problem in Android "RNCAndoidDropdownPicker" was not found in the UI Manager

**Comment by Mahdisaghroun** [comment] 2021-01-22 10:29
same problem in Android "RNCAndoidDropdownPicker" was not found in the UI Manager

**Comment by bachbonglong** [comment] 2021-03-26 05:54
> Restart your simulator after pod install
A wonderful thing happened. It works fine, I don't know why?

**Comment by oxyu8** [comment] 2021-03-30 06:20
I solved the issue with these steps

1. yarn add @react-native-picker/picker
2. npx pod-install
3. cd ios/ && pod install
4. restart my simulator

https://github.com/react-native-picker/picker#for-react-native-v060-and-above-autolinking

**Comment by pwaweru** [comment] 2021-05-05 11:47
Hey I'm still experiencing this problem: 
`Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager.`

I am not using expo, and running the latest version of React Native (0.64).

I have `Picker` imported like so:

`import { Picker } from '@react-native-picker/picker';`

Any ideas?

**Comment by YoucefAcheuk** [comment] 2021-06-04 10:06
I am not using expo and I had the same issue.
This is how i fixed it : 
`cd ios && rm -rf Pods`
`rm -rf node_modules`
`yarn && cd ios && pod install && cd ..`
`yarn add @react-native-picker/picker`

Install [rn-game-over](https://github.com/taboulot/rn-game-over) to clean your React Native project

**Comment by sravanpronteff** [comment] 2021-09-15 07:40
> > As far as I know, this component is still not available in the managed workflow of expo 37.
> > In order to use this component, you would have to eject into a bare workflow, so that other native modules can be used.
> > If you want to use the Picker Component in managed workflow of expo, please import the `Picker` component directly from `react-native.
> > ```
> > import { Picker } from 'react-native'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you may see a deprecated warning, but the component is still usable as it lives in the core.
> 
> Thanks for your comment. Will work with the picker directly from React Native. Do you know if/when this component will become available in the managed workflow of Expo 37?

its not working in IOS

**Comment by abnwoke** [comment] 2021-09-15 11:49
Please how do I style the picker? my styles are not working.

 <Picker
                           selectedValue={selectedLanguage}
                           onValueChange={(itemValue, itemIndex) =>
                               setSelectedLanguage(itemValue)
                           }
                           style={{padding: 0, margin: 0}}
                           mode='dialog' /* dropdown | dialog */
                           prompt="Categories"
                           
                       >
                           <Picker.Item label="Java" value="java" />
                           <Picker.Item label="JavaScript" value="js" />
                       </Picker>

**Comment by abnwoke** [comment] 2021-09-15 12:23
Please how do I add a placeholder to the picker?

**Comment by JohnMendes** [comment] 2021-09-21 13:19
Bom dia 

fiz assim <Picker.Item style={{color:'#fff'}} label="ENTRADA" value={ENTRADA} />

**Comment by DanielAraldi** [comment] 2021-11-26 19:41
I solved this problem in my project by adding this to my `Podfile`:

```yml
target 'ProjectName' do
  config = use_native_modules!

  # ...
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
  # ...
end
```

**Comment by Stephen-L-Wang** [comment] 2021-11-29 11:01
> On RN 66.3 I solved this problem in my project by adding this to my `Podfile`:
> 
> ```yaml
> target 'ProjectName' do
>   config = use_native_modules!
> 
>   # ...
>   pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
>   # ...
> end
> ```

Thanks   It  working

**Comment by MorenoMdz** [comment] 2022-03-19 15:50
Is anybody here experienced in using this library in the new expo custom dev clients? We are getting `"RNCPicker" was not found in the UIManager` when trying to use the library, it works fine in Expo Go (SDK 44)

**Comment by kennyho-ml** [comment] 2022-03-23 18:23
> Is anybody here experienced in using this library in the new expo custom dev clients? We are getting `"RNCPicker" was not found in the UIManager` when trying to use the library, it works fine in Expo Go (SDK 44)

@MorenoMdz -- Had to use `expo update`

**Comment by MorenoMdz** [comment] 2022-03-23 18:52
> > Is anybody here experienced in using this library in the new expo custom dev clients? We are getting `"RNCPicker" was not found in the UIManager` when trying to use the library, it works fine in Expo Go (SDK 44)
> 
> @MorenoMdz -- Had to use `expo update`

Hey, thanks for the response! What we had to do here was create a new iOS simulator build to use in the dev client.

**Comment by Rukt** [comment] 2022-05-16 12:43
> What we had to do here was create a new iOS simulator build to use in the dev client.

It was a similar solution for me on Android:

`expo install @react-native-picker/picker` (2.2.1, per package.json)
`eas build --profile development --platform android` (where the "development" profile has `"developmentClient"; true` and `"android.buildType": "apk"`)
`adb install "path/to/devBuild.apk"`
`expo start --clear --dev-client`

**Comment by Saalim95** [comment] 2023-01-30 04:51
I solved it by:

1. First, run `npm install react-native-picker-select`
2. Then run  `npm install @react-native-picker/picker`
3. `pod install`

**Comment by shreyvijayvargiya** [comment] 2023-08-09 10:27
> ll @react-native-community/picker

This is deprecated!!!

**Comment by janusqa** [comment] 2023-09-04 19:08
I had this issue just pop up. I realize that 
1) When using expo go there is no issue as expo go seems to have this installed by default, that is @react-native-picker/picker
2) If using a dev build I needed to install it manually "npx expo install "@react-native-picker/picker", rebuild the project and that worked.

**Comment by Ant1N** [comment] 2023-09-19 14:58
I'm still getting this error as well. I have tried just about all tips in this thread as well. Any new leads on what might be the issue?

**Comment by AlexKenny6** [comment] 2023-12-01 00:11
I had this issue too and finally found a solution.

I am running Expo SDK 49 and @react-native-picker/picker v 2.4.10 with a managed Expo workflow. 

The picker was working great in Expo Go on iOS simulator and on my physical iPhone. Then was working great when I tested in a staging branch with eas updates. The problem I faced was the app would crash after I clicked on the page that was using the picker in production. After a few hours of tests the solution that I found was to create a new development build with EAS Build. After the build was uploaded to TestFlight, I again tested the Picker and it finally worked.

**Comment by ReMuSoMeGA93** [comment] 2024-02-02 21:52
2024. Still broken. Seems like this project is abandoned.

**Comment by ArunKumar-webdev** [comment] 2024-06-09 12:29
> I solved it by:
> 
> 1. First, run `npm install react-native-picker-select`
> 2. Then run  `npm install @react-native-picker/picker`
> 3. `pod install`

thanks this works.

**Comment by Naturalclar** [comment] 2024-06-10 00:12
For expo projects, please run
`expo install @react-native-picker/picker`

For bare projects, please run
`npm install @react-native-picker/picker`
then run 
`pod install` 
for iOS projects.

**Closed by Naturalclar** 2024-06-10 00:12 UTC
